name: myenv

dependencies:
    - numpy
    - scipy
    - pycbc
    - lalsuite
    - ligo-common
    - matplotlib
    - statistics
    - termcolor
    - h5py
    - numba


channels:
    - defaults
    - conda-forge
