name: myenv

dependencies:
    - python=3.9
    - pycbc
    - lalsuite
    - ligo-common
    - statistics
    - termcolor
    - numba
    - scipy
    - matplotlib
    - h5py

channels:
    - defaults
    - conda-forge
